import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { pythonProject, runPythonProject } from "./support/python-project.mjs";

test("installed late C.R.A.P. compares saved inputs with selected tests and preserves prior debt", async (t) => {
  const { root } = await pythonProject(t);
  const source = "work dir/src/subject.py";
  const chosen = "work dir/python checks/check_subject.py";
  const alternate = "work dir/python checks/check_other.py";
  await writeFile(path.join(root, alternate), "from src.subject import classify\ndef test_other():\n    assert classify(1) == 'positive'\n");
  const original = await readFile(path.join(root, source), "utf8");
  const debt = original + "\ndef uncovered(value):\n    if value > 0:\n        return 1\n    if value < 0:\n        return -1\n    return 0\n";
  await writeFile(path.join(root, source), debt);
  const invoke = async (...args) => {
    const result = await runPythonProject(root, args);
    return { ...JSON.parse(result.stdout), processCode: result.code };
  };
  const prepared = await invoke("prepare", "--task", "late-crap", "--mode", "direct", "--objective", "issue:91");
  assert.equal(prepared.processCode, 0, JSON.stringify(prepared));
  const initial = await readFile(path.join(root, ".agentic-core/quality/active-task.json"));
  assert.equal(JSON.parse(initial).task.initial.quality.crap.executed, false);
  await writeFile(path.join(root, source), debt + "\n# task change\n");
  const args = ["verify", "--control", "crap", "--scope", source, "--test", chosen];
  const first = await invoke(...args);
  assert.equal(first.processCode, 0, JSON.stringify(first));
  const report = first.verification.crap;
  assert.equal(report.details.find((row) => row.name === "uncovered").rule, "preexisting_debt_must_not_worsen");
  assert.deepEqual(report.initialMeasurement.execution.suite.executed.map((row) => row.path), [chosen]);
  assert.deepEqual(report.execution.suite.executed.map((row) => row.path), [chosen]);
  assert.notEqual(report.initialMeasurement.inputs.digest, report.inputs.digest);
  for (const name of ["dry", "mutation"]) assert.equal(first.verification[name].executed, false);
  assert.equal((await invoke(...args)).verification.reuse.crap.reused, true);
  assert.equal((await invoke("explain", "--json")).evidence.current, true);
  const current = await invoke("crap", "--scope", source, "--test", chosen);
  assert.equal(current.processCode, 1, JSON.stringify(current));
  await writeFile(path.join(root, source), debt.replace("    return 0", "    if value == 7:\n        return 7\n    return 0"));
  const worse = await invoke(...args);
  assert.equal(worse.processCode, 1, JSON.stringify(worse));
  assert.ok(worse.verification.crap.details.find((row) => row.name === "uncovered").delta > 0);
  await writeFile(path.join(root, source), debt + "\n# corrected\n");
  const fixed = await invoke("verify", "--control", "crap", "--changes", "--test", chosen);
  assert.equal(fixed.processCode, 0, JSON.stringify(fixed));
  const other = await invoke("verify", "--control", "crap", "--scope", source, "--test", alternate);
  assert.equal(other.processCode, 0, JSON.stringify(other));
  assert.equal(other.verification.reuse.crap.reused, false);
  assert.deepEqual(other.verification.crap.initialMeasurement.execution.suite.executed.map((row) => row.path), [alternate]);
  assert.deepEqual(await readFile(path.join(root, ".agentic-core/quality/active-task.json")), initial);
  const next = await invoke("prepare", "--task", "next", "--mode", "direct", "--objective", "next");
  assert.equal(next.processCode, 0, JSON.stringify(next));
  assert.equal((await invoke("verify")).verification.crap.status, "NO_SOLICITADO");
  const unloaded = "work dir/src/unloaded.py";
  await writeFile(path.join(root, unloaded), "def unobserved():\n    return 42\n");
  assert.equal((await invoke("prepare", "--task", "insufficient", "--mode", "direct", "--objective", "unknown baseline")).processCode, 0);
  await writeFile(path.join(root, chosen), `${await readFile(path.join(root, chosen), "utf8")}\nfrom src.unloaded import unobserved\ndef test_loaded():\n    assert unobserved() == 42\n`);
  const incomplete = await invoke("verify", "--control", "crap", "--scope", unloaded, "--test", chosen);
  assert.equal(incomplete.processCode, 2, JSON.stringify(incomplete));
  assert.equal(incomplete.verification.crap.initialMeasurement.code, "coverage_failed");
  assert.equal(incomplete.verification.crap.status, "NO_VERIFICADO");
});
