import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { configurePythonProject, pythonProject, runPythonProject } from "./support/python-project.mjs";

async function crap(root) {
  const result = await runPythonProject(root, ["crap"]);
  assert.equal(result.stderr, "");
  return { ...result, report: JSON.parse(result.stdout) };
}

test("installed crap4py uses authoritative coverage, the configured boundary and reproducible identities", async (t) => {
  const { root } = await pythonProject(t);
  const file = path.join(root, "work dir/src/subject.py");
  const original = await readFile(file);
  const first = await crap(root);
  assert.equal(first.code, 0, first.stdout);
  assert.equal(first.report.status, "approved");
  assert.equal(first.report.engine.version, "0.1.1");
  assert.equal(first.report.execution.suite.status, "passed");
  const row = first.report.details.find((entry) => entry.name === "classify");
  assert.equal(row.complexity, 2);
  assert.equal(row.coverage.fraction, 1);
  assert.equal(row.value, 2);
  assert.equal(row.limit, 7);
  assert.equal(first.report.details.length, 1, "function-only declarations are not scored twice as a module");
  assert.ok(!first.stdout.includes(root));
  const repeated = await crap(root);
  assert.deepEqual(repeated.report.details, first.report.details);
  assert.equal(repeated.report.identity, first.report.identity);
  await configurePythonProject(root, (config) => { config.limits.crap = 2; });
  assert.equal((await crap(root)).code, 0, "a value at the configured limit is accepted");
  await configurePythonProject(root, (config) => { config.limits.crap = 1.5; });
  const strict = await crap(root);
  assert.equal(strict.code, 1, strict.stdout);
  assert.equal(strict.report.details[0].limit, 1.5);
  assert.notEqual(strict.report.identity, first.report.identity);
  const human = await runPythonProject(root, ["crap"], { AGENTIC_CORE_OUTPUT: "text" });
  assert.equal(human.code, 1);
  assert.match(human.stdout, /work dir\/src\/subject.py:1 classify: 2; límite 1.5/u);
  assert.match(human.stdout, /Informe íntegro: \.agentic-core\/quality\/crap.json/u);
  assert.ok(human.stdout.split("\n").length <= 5);
  const saved = await readFile(path.join(root, strict.report.reference));
  await configurePythonProject(root, (config) => { config.limits.crap = -1; });
  const invalid = await crap(root);
  assert.equal(invalid.code, 4);
  assert.equal(invalid.report.code, "invalid_configuration");
  assert.deepEqual(await readFile(path.join(root, strict.report.reference)), saved);
  assert.deepEqual(await readFile(file), original);
});

test("installed C.R.A.P. preserves zero coverage and supported metrics without approving unloaded or unsupported parts", async (t) => {
  const { root } = await pythonProject(t);
  const subject = path.join(root, "work dir/src/subject.py");
  await writeFile(subject, `${await readFile(subject, "utf8")}\ndef uncovered(value):\n    if value > 0:\n        return 1\n    if value < 0:\n        return -1\n    return 0\n\ndef branchless():\n    return 42\n\nasync def asynchronous(values):\n    async for value in values:\n        if value:\n            return 1\n    return 0\n`);
  const zero = await crap(root);
  assert.equal(zero.code, 1, zero.stdout);
  const uncovered = zero.report.details.find((row) => row.name === "uncovered");
  assert.equal(uncovered.coverage.status, "zero");
  assert.equal(uncovered.coverage.fraction, 0);
  assert.equal(uncovered.complexity, 3);
  assert.equal(uncovered.value, 12);
  const branchless = zero.report.details.find((row) => row.name === "branchless");
  assert.equal(branchless.coverage.fraction, 0);
  assert.equal(branchless.coverage.basis, "statements");
  assert.equal(branchless.value, 2, "absence of branches does not fabricate complete coverage");
  const asynchronous = zero.report.details.find((row) => row.name === "asynchronous");
  assert.equal(asynchronous.complexity, 3);
  assert.equal(asynchronous.coverage.fraction, 0);
  assert.equal(asynchronous.value, 12);
  await writeFile(path.join(root, "work dir/src/unloaded.py"), "def absent(value):\n    if value:\n        return 1\n    return 0\n");
  await writeFile(path.join(root, "work dir/src/bad.py"), "def broken(:\n    pass\n");
  await writeFile(path.join(root, "work dir/src/foreign.js"), "export const value = 1;\n");
  const partial = await crap(root);
  assert.equal(partial.code, 2, partial.stdout);
  assert.equal(partial.report.status, "NO_VERIFICADO");
  assert.equal(partial.report.details.find((row) => row.name === "classify").value, 2);
  assert.equal(partial.report.details.find((row) => row.name === "uncovered").value, 12);
  const absent = partial.report.details.find((row) => row.name === "absent");
  assert.equal(absent.code, "coverage_not_loaded");
  assert.equal(absent.value, null);
  assert.equal(absent.coverage.fraction, null);
  assert.equal(partial.report.details.find((row) => row.file.endsWith("bad.py")).code, "unsupported_syntax");
  assert.equal(partial.report.details.find((row) => row.file.endsWith("foreign.js")).code, "unsupported_language");
  assert.doesNotMatch(partial.stdout, /QUALITY_OK/);
  await configurePythonProject(root, (config) => { config.integration.python.scope = ["work dir/src/unloaded.py"]; });
  const unloadedScope = await crap(root);
  assert.equal(unloadedScope.code, 2, unloadedScope.stdout);
  assert.equal(unloadedScope.report.details[0].code, "coverage_not_loaded");
  assert.equal(unloadedScope.report.details[0].value, null);
  await configurePythonProject(root, (config) => { config.integration.python.scope = ["work dir/src"]; });
  const wrapper = path.join(root, "work dir/wrapper space.py");
  await writeFile(wrapper, (await readFile(wrapper, "utf8")).replace("raise SystemExit", "os.environ.pop('PYTEST_PLUGINS', None)\nraise SystemExit"));
  const unattributed = await crap(root);
  assert.equal(unattributed.code, 2, unattributed.stdout);
  assert.equal(unattributed.report.execution.code, "pytest_unobserved");
  assert.equal(unattributed.report.details.find((row) => row.name === "classify").code, "coverage_attribution_missing");
  assert.equal(unattributed.report.details.find((row) => row.name === "classify").value, null);
});

test("installed module ownership excludes function bodies and exposes analysis limitations", async (t) => {
  const { root } = await pythonProject(t);
  const subject = path.join(root, "work dir/src/subject.py");
  const source = await readFile(subject, "utf8");
  await writeFile(subject, `${source}\nvalues = [1, 2]\nif values:\n    selected = values[0]\nelse:\n    selected = 0\n`);
  const result = await crap(root);
  assert.equal(result.code, 0, result.stdout);
  const module = result.report.details.find((row) => row.kind === "module");
  const fn = result.report.details.find((row) => row.name === "classify");
  assert.equal(module.complexity, 2);
  assert.equal(module.coverage.fraction, 0.5);
  assert.equal(module.value, 2.5);
  assert.equal(fn.complexity, 2);
  assert.equal(fn.value, 2);
  assert.deepEqual(module.coverage.executedLines.filter((line) => fn.coverage.executedLines.includes(line)), []);
  await writeFile(subject, `${await readFile(subject, "utf8")}\ndeferred = lambda value: 1 if value else 0\n`);
  const limited = await crap(root);
  assert.equal(limited.code, 2, limited.stdout);
  assert.equal(limited.report.details.find((row) => row.kind === "module").code, "unsupported_construct");
  assert.equal(limited.report.details.find((row) => row.name === "classify").value, 2);
  await writeFile(path.join(root, limited.report.reference), "informe ajeno\n");
  const unsaved = await crap(root);
  assert.equal(unsaved.report.code, "quality_report_conflict");
  assert.equal(unsaved.report.details.find((row) => row.name === "classify").value, 2);
  assert.equal(unsaved.report.reference, undefined);
});

test("installed C.R.A.P. explains a documentation-only scope and preserves a foreign report", async (t) => {
  const { root } = await pythonProject(t);
  await writeFile(path.join(root, "guide.md"), "# Guía del proyecto\n");
  await configurePythonProject(root, (config) => { config.integration.python.scope = ["guide.md"]; });
  const result = await crap(root);
  assert.equal(result.code, 0, result.stdout);
  assert.equal(result.report.status, "NO_APLICA");
  assert.equal(result.report.code, "no_executable_code");
  assert.deepEqual(result.report.details, []);
  const reportFile = path.join(root, result.report.reference);
  await writeFile(reportFile, "contenido ajeno\n");
  const conflict = await crap(root);
  assert.equal(conflict.code, 2);
  assert.equal(conflict.report.code, "quality_report_conflict");
  assert.equal(await readFile(reportFile, "utf8"), "contenido ajeno\n");
});
